//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTNAME
    {
        public string OLDCODE { get; set; }
        public string NEWCODE { get; set; }
        public string LEVEL { get; set; }
    }
}
