//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAMEMAP
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string SHNAME { get; set; }
        public string SCNAME { get; set; }
    }
}
