//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREET
    {
        public string NAME { get; set; }
        public string SOCR { get; set; }
        public string CODE { get; set; }
        public string INDEX { get; set; }
        public string GNINMB { get; set; }
        public string UNO { get; set; }
        public string OCATD { get; set; }
    }
}
